// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Backend.Migrations {
	[DbContext(typeof(FrotaContext))]
	[Migration("20210501154747_CreateFrotaDB")]
	partial class CreateFrotaDB {
		protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("ProductVersion", "5.0.5")
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Backend.Veiculo", b => {
				b.Property<int>("id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("cor").HasColumnType("nvarchar(max)");

				b.Property<int>("idMarca").HasColumnType("int");

				b.Property<string>("nome").HasColumnType("nvarchar(max)");

				b.HasKey("id");

				b.HasIndex("idMarca");

				b.ToTable("carro");
			});

			modelBuilder.Entity("Backend.Marca", b => {
				b.Property<int>("id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("idPais").HasColumnType("int");

				b.Property<string>("nome").HasColumnType("nvarchar(max)");

				b.HasKey("id");

				b.HasIndex("idPais");

				b.ToTable("marks");
			});

			modelBuilder.Entity("Backend.Pais", b => {
				b.Property<int>("id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int")
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Nome").HasColumnType("nvarchar(max)");

				b.HasKey("id");

				b.ToTable("countries");
			});

			modelBuilder.Entity("Backend.Veiculo", b => {
				b.HasOne("Backend.Marca", "Marca")
					.WithMany()
					.HasForeignKey("idMarca")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("Marca");
			});

			modelBuilder.Entity("Backend.Marca", b => {
				b.HasOne("Backend.Pais", "Pais")
					.WithMany()
					.HasForeignKey("idPais")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();

				b.Navigation("Pais");
			});
#pragma warning restore 612, 618
		}
	}
}
